"""Shared risk-scoring and actor-matching helpers.

These exist so the analyzer, repository, and correlator all agree on the
thresholds for "LOW / MEDIUM / HIGH / CRITICAL" and on what counts as "the
same actor". The earlier implementation duplicated both definitions, with
slightly different rules in each location; consolidating them removes a
class of "same actor, different risk score" bugs.
"""

from __future__ import annotations

from .events.models import SecurityEvent


def clamp_risk_score(score: float) -> float:
    """Normalize any risk score to the public 0-10 scale."""
    return round(max(0.0, min(10.0, float(score))), 1)


def score_to_risk_level(score: float) -> str:
    """Map a 0-10 numeric score to a categorical risk level.

    Thresholds:
        >= 8.0 -> CRITICAL
        >= 6.0 -> HIGH
        >= 3.0 -> MEDIUM
        else   -> LOW
    """
    if score >= 8.0:
        return "CRITICAL"
    if score >= 6.0:
        return "HIGH"
    if score >= 3.0:
        return "MEDIUM"
    return "LOW"


def actor_matches(event: SecurityEvent, actor_id: str) -> bool:
    """Return True if `event` was generated by `actor_id`.

    An event is considered a match when:
    - the event's `actor.username` equals `actor_id`
    - or the event's `actor.user_id` equals `actor_id`
    - or the event's `actor.arn` equals or contains `actor_id`

    This is the union of the two prior implementations (the in-memory
    repository and the local analyzer), so any caller that was using
    either set of rules now sees the same answer.
    """
    if not actor_id or not event.actor:
        return False
    if event.actor.username == actor_id:
        return True
    if event.actor.user_id == actor_id:
        return True
    return bool(event.actor.arn and (event.actor.arn == actor_id or actor_id in event.actor.arn))
