"""Security event repository implementation."""

from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime
from typing import Protocol

from .models import SecurityEvent


class EventRepository(Protocol):
    """Interface for storing and retrieving normalized security events."""

    def save(self, event: SecurityEvent) -> None:
        """Persist a normalized security event."""
        ...

    def get(
        self,
        *,
        actor_id: str,
        event_time: datetime,
        event_id: str,
    ) -> SecurityEvent | None:
        """Retrieve one event using its primary identity."""
        ...

    def query_by_actor(
        self,
        *,
        actor_id: str,
        start_time: datetime | None = None,
        end_time: datetime | None = None,
    ) -> Sequence[SecurityEvent]:
        """Retrieve events generated by an actor."""
        ...

    def query_by_resource(
        self,
        *,
        resource_id: str,
        start_time: datetime | None = None,
        end_time: datetime | None = None,
    ) -> Sequence[SecurityEvent]:
        """Retrieve events associated with a resource."""
        ...

    def query_by_severity(
        self,
        *,
        severity: str,
        start_time: datetime | None = None,
        end_time: datetime | None = None,
    ) -> Sequence[SecurityEvent]:
        """Retrieve events matching a severity level."""
        ...

    def query_by_source_ip(
        self,
        *,
        ip_address: str,
        start_time: datetime | None = None,
        end_time: datetime | None = None,
    ) -> Sequence[SecurityEvent]:
        """Retrieve events by source IP address."""
        ...

    def query_by_time_range(
        self,
        start_time: datetime | None = None,
        end_time: datetime | None = None,
    ) -> Sequence[SecurityEvent]:
        """Retrieve events within a time range."""
        ...

    def list_all_actors(self) -> list[str]:
        """List all unique actor IDs in the repository."""
        ...
